var annotated_dup =
[
    [ "Codigo", "class_codigo.html", "class_codigo" ],
    [ "CodigoTest", "class_codigo_test.html", null ],
    [ "Data", "class_data.html", "class_data" ],
    [ "DataTest", "class_data_test.html", null ],
    [ "Email", "class_email.html", "class_email" ],
    [ "EmailTest", "class_email_test.html", null ],
    [ "Estado", "class_estado.html", "class_estado" ],
    [ "EstadoTest", "class_estado_test.html", null ],
    [ "HistoriaUsuario", "class_historia_usuario.html", "class_historia_usuario" ],
    [ "HistoriaUsuarioTest", "class_historia_usuario_test.html", null ],
    [ "Nome", "class_nome.html", "class_nome" ],
    [ "NomeTest", "class_nome_test.html", null ],
    [ "Papel", "class_papel.html", "class_papel" ],
    [ "PapelTest", "class_papel_test.html", null ],
    [ "Pessoa", "class_pessoa.html", "class_pessoa" ],
    [ "PessoaTest", "class_pessoa_test.html", null ],
    [ "PlanoSprint", "class_plano_sprint.html", "class_plano_sprint" ],
    [ "PlanoSprintTest", "class_plano_sprint_test.html", null ],
    [ "Prioridade", "class_prioridade.html", "class_prioridade" ],
    [ "PrioridadeTest", "class_prioridade_test.html", null ],
    [ "Projeto", "class_projeto.html", "class_projeto" ],
    [ "ProjetoTest", "class_projeto_test.html", null ],
    [ "Senha", "class_senha.html", "class_senha" ],
    [ "SenhaTest", "class_senha_test.html", null ],
    [ "Tempo", "class_tempo.html", "class_tempo" ],
    [ "TempoTest", "class_tempo_test.html", null ],
    [ "Texto", "class_texto.html", "class_texto" ],
    [ "TextoTest", "class_texto_test.html", null ]
];